# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: $(Rev:r)

trigger:
- master

resources:
  repositories:
    - repository: self
  pipelines:
    - pipeline: integration-tests-ci
      source: ikolomiyets.demo-integration-tests
      trigger:
        branches:
          - master

variables:
  - group: demo
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Prepare manifests
  jobs:
  - job: Prepare
    displayName: Prepare deployment manifests
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '.'
        ArtifactName: 'swarm'
        publishLocation: 'Container'
